from enum import unique, IntEnum

<enum 'NutrientID'>

NUTRIENT_METADATA = {
    NutrientID.PROTEIN: {'name': 'Protein', 'unit_name': 'G'},
    NutrientID.FAT: {'name': 'Total lipid (fat)', 'unit_name': 'G'},
    NutrientID.CARBOHYDRATE: {'name': 'Carbohydrate, by difference', 'unit_name': 'G'},
    NutrientID.ASH: {'name': 'Ash', 'unit_name': 'G'},
    NutrientID.ENERGY: {'name': 'Energy', 'unit_name': 'KCAL'},
    NutrientID.WATER: {'name': 'Water', 'unit_name': 'G'},
    NutrientID.FIBER: {'name': 'Fiber, total dietary', 'unit_name': 'G'},
    NutrientID.CALCIUM: {'name': 'Calcium, Ca', 'unit_name': 'MG'},
    NutrientID.CHLORIDE: {'name': 'Chlorine, Cl', 'unit_name': 'MG'},
    NutrientID.IRON: {'name': 'Iron, Fe', 'unit_name': 'MG'},
    NutrientID.MAGNESIUM: {'name': 'Magnesium, Mg', 'unit_name': 'MG'},
    NutrientID.PHOSPHORUS: {'name': 'Phosphorus, P', 'unit_name': 'MG'},
    NutrientID.POTASSIUM: {'name': 'Potassium, K', 'unit_name': 'MG'},
    NutrientID.SODIUM: {'name': 'Sodium, Na', 'unit_name': 'MG'},
    NutrientID.ZINC: {'name': 'Zinc, Zn', 'unit_name': 'MG'},
    NutrientID.COPPER: {'name': 'Copper, Cu', 'unit_name': 'MG'},
    NutrientID.IODINE: {'name': 'Iodine, I', 'unit_name': 'UG'},
    NutrientID.MANGANESE: {'name': 'Manganese, Mn', 'unit_name': 'MG'},
    NutrientID.SELENIUM: {'name': 'Selenium, Se', 'unit_name': 'UG'},
    NutrientID.VITAMIN_A: {'name': 'Vitamin A, IU', 'unit_name': 'IU'},
    NutrientID.VITAMIN_E: {'name': 'Vitamin E (alpha-tocopherol)', 'unit_name': 'MG'},
    NutrientID.VITAMIN_D: {'name': 'Vitamin D (D2 + D3), International Units', 'unit_name': 'IU'},
    NutrientID.THIAMIN: {'name': 'Thiamin', 'unit_name': 'MG'},
    NutrientID.RIBOFLAVIN: {'name': 'Riboflavin', 'unit_name': 'MG'},
    NutrientID.NIACIN: {'name': 'Niacin', 'unit_name': 'MG'},
    NutrientID.PANTOTHENIC_ACID: {'name': 'Pantothenic acid', 'unit_name': 'MG'},
    NutrientID.PYRIDOXINE: {'name': 'Vitamin B-6', 'unit_name': 'MG'},
    NutrientID.VITAMIN_B12: {'name': 'Vitamin B-12', 'unit_name': 'UG'},
    NutrientID.CHOLINE: {'name': 'Choline, total', 'unit_name': 'MG'},
    NutrientID.FOLIC_ACID: {'name': 'Folic acid', 'unit_name': 'UG'},
    NutrientID.TRYPTOPHAN: {'name': 'Tryptophan', 'unit_name': 'G'},
    NutrientID.THREONINE: {'name': 'Threonine', 'unit_name': 'G'},
    NutrientID.ISOLEUCINE: {'name': 'Isoleucine', 'unit_name': 'G'},
    NutrientID.LEUCINE: {'name': 'Leucine', 'unit_name': 'G'},
    NutrientID.LYSINE: {'name': 'Lysine', 'unit_name': 'G'},
    NutrientID.METHIONINE: {'name': 'Methionine', 'unit_name': 'G'},
    NutrientID.CYSTINE: {'name': 'Cystine', 'unit_name': 'G'},
    NutrientID.PHENYLALANINE: {'name': 'Phenylalanine', 'unit_name': 'G'},
    NutrientID.TYROSINE: {'name': 'Tyrosine', 'unit_name': 'G'},
    NutrientID.VALINE: {'name': 'Valine', 'unit_name': 'G'},
    NutrientID.ARGININE: {'name': 'Arginine', 'unit_name': 'G'},
    NutrientID.HISTIDINE: {'name': 'Histidine', 'unit_name': 'G'},
    NutrientID.LA: {'name': 'PUFA 18:2', 'unit_name': 'G'},
    NutrientID.ARA: {'name': 'PUFA 20:4', 'unit_name': 'G'},
    NutrientID.DHA: {'name': 'PUFA 22:6 n-3 (DHA)', 'unit_name': 'G'},
    NutrientID.EPA: {'name': 'PUFA 20:5 n-3 (EPA)', 'unit_name': 'G'},
    NutrientID.ALA: {'name': 'PUFA 18:3 n-3 c,c,c (ALA)', 'unit_name': 'G'},
}
